### PR TITLE
Adding stylesheet and page header templates

### PR DESCRIPTION
**Pull request by RedstoneFuture**
**Description**
- Adding stylesheet file
- Adding template file
- Standardization of the page header with the template
- the Table of Content down't show the "return to index" link anymore

----

Screenshot 2022-07-25 013855

----

**Submitter Checklist**

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the proposed change appropriately.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by NotMyFault** [comment]
Hey,

thanks for the PR! One question: How did you test your changes locally? If I parse adoc to html the following is generated:
Screenshot 2022-07-27 at 16 29 00
And that doesn't quite match your screenshots.

**Comment by RedstoneFuture** [comment]
@NotMyFault

I'm not sure, but your screenshot looks like it didn't use any style at all. Not even the default style of AsciiDoc.

1. With the IntelliJ plugin [AsciiDoc](https://plugins.jetbrains.com/plugin/7391-asciidoc)

Screenshot 2022-07-27 185733

2. With a custom-stylesheet add-on for my browser

Screenshot 2022-07-27 185937

**Comment by NotMyFault** [comment]
I created https://github.com/IntellectualSites/plotsquared-documentation-staging pulling in your change and the missing style sheet applies there too.

Under the hood, the action invokes the asciidoctor command line action to generate the .html file. If you got it installed locally, you can use it by invoking its name to build your changes.

**Comment by Xaver106** [comment]
@NotMyFault You need to set asciidoctor to server or safe mode, so it embeds the stylesheet in to the html itself. Otherwise it will just link it, which will not work if the stylesheet is only locally present.
[Link to relevant asciidoctor docs](https://docs.asciidoctor.org/asciidoctor/latest/html-backend/stylesheet-modes/)

**Comment by NotMyFault** [comment]
> You need to set asciidoctor to server or safe mode

Please set whatever is needed on the staging instance.

**Comment by RedstoneFuture** [comment]
> > You need to set asciidoctor to server or safe mode
> 
> Please set whatever is needed on the staging instance.

If I have understood this correctly, you set the safe-mode with CLI and not in the `.adoc` files.
https://docs.asciidoctor.org/asciidoctor/latest/cli/set-safe-mode/

Edit: I'll see what I can do again.

**Comment by NotMyFault** [comment]
Thanks for proposing the change.

A few ideas:
- The sidebar shouldn't be in be in dark mode by default, leaving it in its default color seems better.
- https://intellectualsites.github.io/plotsquared-documentation-staging/optimization/chunk-processor.html doesn't use the new sidebar
- Screenshot 2022-08-04 at 11 03 23
 You changed the house emoji to something browsers can't render, why?

I invited Xaver to the staging repo, feel free to push your changes.

**Comment by RedstoneFuture** [comment]
> You changed the house emoji to something browsers can't render, why?

The Unicode house is often represented as Emoji:

grafik


And the new arrow works fine in desktop browsers. But on my phone I have the same problem that it is not displayed.

grafik

**Comment by OneLiteFeather** [comment]
What about this one? Is there still issues with the unicode?

**Comment by RedstoneFuture** [comment]
It is more complicated. Last year, Xaver and I revised the AscciiDoc Documentation System (representative for PlotSquared) in the [test project](https://github.com/IntellectualSites-Internal/plotsquared-documentation-staging/commits/main). It's ready so far, but would just need to be final-tested by NotMyFault and transferred to the main project. Here, however, was also updated the docs from time to time.

The revision here is the minimum to make the documentary at all somewhat respectable. With this rework, we have again noticed that AsciiDoc has some peculiarities (like [this](https://github.com/asciidoctor/asciidoctor/issues/1903)) that make many customizations difficult.

I still think that there are more modern documentation systems with a much better structure and more functions. For example, I would rather use [GitBook](https://www.gitbook.com/) or [MkDoc](https://www.mkdocs.org/getting-started/).

**Comment by RedstoneFuture** [comment]
A complete rework of the documentation page is already in progress: https://github.com/IntellectualSites/documentation We use GitBook now.

**Pull request closed without merging**
